from __future__ import annotations

from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
for p in [
    ROOT / 'app' / 'schemas',
    ROOT / 'app' / 'providers',
    ROOT / 'app' / 'agents',
    ROOT / 'app' / 'pipeline',
    ROOT / 'app' / 'render',
    ROOT / 'tasks',
    ROOT / 'cache',
    ROOT / 'logs',
    ROOT / 'outputs',
]:
    p.mkdir(parents=True, exist_ok=True)

files: dict[str, str] = {}

files[f'{ROOT}/.env.example'] = '''# StepFun\nSTEPFUN_API_KEY=\nSTEPFUN_BASE_URL=https://api.stepfun.com/step_plan/v1\nSTEPFUN_MODEL_FAST=step-3.7-flash\nSTEPFUN_MODEL_AGENT=step-explore\nSTEPFUN_MODEL_REASONING=step-explore\nSTEPFUN_MODEL_VISION=step-1o-turbo-vision\nSTEPFUN_MODEL_IMAGE=step-image-edit-2\nSTEPFUN_MODEL_TTS=stepaudio-2.5-tts\nSTEPFUN_ROUTER_MODEL=step-router-v1\nSTEPFUN_ENABLE_ROUTER=false\nSTEPFUN_TIMEOUT=60\nSTEPFUN_MAX_RETRIES=3\n\n# GitHub\nGITHUB_TOKEN=\n\n# App\nLOG_LEVEL=INFO\n'''

files[f'{ROOT}/.gitignore'] = '''# Python\n.venv/\n__pycache__/\n*.pyc\n\n# Env and secrets\n.env\n\n# Data directories generated by pipeline\ntasks/\ncache/\nlogs/\noutputs/\n'''

files[f'{ROOT}/requirements.txt'] = '''httpx==0.28.1\npydantic==2.13.4\npython-dotenv==1.2.3\ntyper==0.27.1\ntenacity==9.1.4\n'''

for rel in [
    'app/__init__.py',
    'app/schemas/__init__.py',
    'app/providers/__init__.py',
    'app/agents/__init__.py',
    'app/pipeline/__init__.py',
    'app/render/__init__.py',
]:
    files[f'{ROOT}/{rel}'] = ''

for path, content in files.items():
    Path(path).write_text(content, encoding='utf-8')

print('SKELETON_OK')
